### ISSUE TITLE
Set up some tests

### ISSUE THREAD

**Issue by NotSqrt** [mattermost/mattermost-integration-gitlab#12]
@it33 @jwilander You are the main contributors of the project.

Are you familiar enough with python and tests in python to set up some tests ?

What I have in mind :
- JSON examples of data sent by hooks (I am not sure than gitlab documentation is up-to-date..)
- tox to test on multiple python versions
- decoupling of the web app so that each type of hook can be easily tested

Thanks

**Comment by jwilander** [comment]
Hi @NotSqrt, sorry for the late response. I think Python tests are really beyond the scope of this integration but if you'd like to set something up feel free to

**Comment by NotSqrt** [comment]
Have a look at https://github.com/NotSqrt/mattermost-integration-gitlab if you want to see what I've done !

**Comment by NotSqrt** [comment]
Done in my repository
