### ISSUE TITLE
Integration with CI webhooks

### ISSUE THREAD

**Issue by NotSqrt** [mattermost/mattermost-integration-gitlab#8]
Hi !

Integration with gitlab's regular webhooks is nice !

Next step: CI webhooks !

Thanks !

**Comment by jerbob92** [comment]
:+1:

**Comment by on99** [comment]
Is there anyone working on gitlab-ci integration? As I want mattermost report if my build is success/errored/failed.

**Comment by NotSqrt** [comment]
Work is on my repository now
